import {CLOUDINARY_NAME,CLOUDINARY_PRESET} from '../config'

const CONSTANTS = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  SET_SESSION: 'SET_SESSION',
  SIGN_OFF: 'SIGN_OFF',
  CLEAN_SIGNUP_IMAGE: 'CLEAN_SIGNUP_IMAGE',
  UPLOAD_SIGNUP_IMAGE: 'UPLOAD_SIGNUP_IMAGE',
  CLOUDINARY_NAME,
  CLOUDINARY_PRESET
}

export default CONSTANTS